
mod_id=blockydoors
curse_id=453072
curse_slug=blocky-doors
mod_version=1.0.1
mod_name=blockydoors
mod_group_id=com.lothrazar.blockydoors
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=blocky-doors

flib_version=0.2.8
flib_file=8482026


